config/routes.rb
Rails.application.routes.draw do
  root 'buks#index'
  resources :buks
  mount API::Root => '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buk.rb
class Buk < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buks_controller.rb
class BuksController < ApplicationController
  before_action :set_buk, only: [:show, :edit, :update, :destroy]

  # GET /buks
  # GET /buks.json
  def index
    @buks = Buk.all
  end

  # GET /buks/1
  # GET /buks/1.json
  def show
  end

  # GET /buks/new
  def new
    @buk = Buk.new
  end

  # GET /buks/1/edit
  def edit
  end

  # POST /buks
  # POST /buks.json
  def create
    @buk = Buk.new(buk_params)

    respond_to do |format|
      if @buk.save
        format.html { redirect_to @buk, notice: 'Buk was successfully created.' }
        format.json { render :show, status: :created, location: @buk }
      else
        format.html { render :new }
        format.json { render json: @buk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buks/1
  # PATCH/PUT /buks/1.json
  def update
    respond_to do |format|
      if @buk.update(buk_params)
        format.html { redirect_to @buk, notice: 'Buk was successfully updated.' }
        format.json { render :show, status: :ok, location: @buk }
      else
        format.html { render :edit }
        format.json { render json: @buk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buks/1
  # DELETE /buks/1.json
  def destroy
    @buk.destroy
    respond_to do |format|
      format.html { redirect_to buks_url, notice: 'Buk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buk
      @buk = Buk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buk_params
      params.require(:buk).permit(:title, :description, :image_url, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buks_helper.rb
module BuksHelper
end

app/views/buks/_form.html.erb
<%= form_with(model: buk, local: true) do |form| %>
  <% if buk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(buk.errors.count, "error") %> prohibited this buk from being saved:</h2>

      <ul>
      <% buk.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 10, cols: 26 %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buks/edit.html.erb
<h1>Editing Buk</h1>

<%= render 'form', buk: @buk %>

<%= link_to 'Show', @buk %> |
<%= link_to 'Back', buks_path %>

app/views/buks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buks</h1>
<%= react_component("HelloWorld", { greeting: "Hello from react-rails." }) %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buks.each do |buk| %>
      <tr>
        <td><%= buk.title %></td>
        <td><%= buk.description %></td>
        <td><%= buk.image_url %></td>
        <td><%= buk.author %></td>
        <td><%= link_to 'Show', buk %></td>
        <td><%= link_to 'Edit', edit_buk_path(buk) %></td>
        <td><%= link_to 'Destroy', buk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buk', new_buk_path %>

app/views/buks/new.html.erb
<h1>New Buk</h1>

<%= render 'form', buk: @buk %>

<%= link_to 'Back', buks_path %>

app/views/buks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @buk.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @buk.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @buk.image_url %>
</p>

<p>
  <strong>Author:</strong>
  <%= @buk.author %>
</p>

<%= link_to 'Edit', edit_buk_path(@buk) %> |
<%= link_to 'Back', buks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>